name: prcheck

on:
  pull_request:
    branches: 
      - dev

jobs:
  devcheck:
    if: ! contains(github.event.head_commit.message, '[skip ci]')
    name: PR check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
#       - name: Try to fail
#       run: exit 1
