name: prcheck

on:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:

  devcheck:
    name: PR check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
#       - name: Try to fail
#       run: exit 1

