name: qa

on:
  push:
    branches: [ qa ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
